version: "3.8"

services:
    mysqldb:
        image: mysql:5.7
        restart: unless-stopped
        env_file: ./.env
        environment:
        - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE=$MYSQL_DATABASE
        # So you don't have to use root, but you can if you like
        - MYSQL_USER=$MYSQL_USER
        # You can use whatever password you like
        - MYSQL_PASSWORD=$MYSQL_PASSWORD
        ports:
        - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
        expose:
            - '3306'
        volumes:
        - db:/var/lib/mysql

    api:
        depends_on:
        - mysqldb
        restart: on-failure
        env_file: ./.env
        build: './ClubRegistry'
        ports:
        - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
        environment:
            SPRING_APPLICATION_JSON: '{
                "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQL_DOCKER_PORT/$MYSQL_DATABASE?reconnect=true",
                "spring.datasource.username" : "$MYSQL_USER",
                "spring.datasource.password" : "$MYSQL_ROOT_PASSWORD",
                "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
                "spring.jpa.hibernate.ddl-auto" : "update"
                }'
        volumes:
        - .m2:/root/.m2
        stdin_open: true
        tty: true

    frontend:
        depends_on:
        - api
        restart: on-failure
        env_file: ./.env
        build: './clubRegistryFrontend'
        ports:
        - 8000:8000

volumes:
  db:
